### ISSUE TITLE
Fazer deploy da pagina automaticamente via travis-ci

### ISSUE THREAD

**Issue by luzfcb** [pythonbrasil/pythonbrasil12-site#12]
- [x] Ativar travis-ci pela conta do github da python-brasil ou por pela conta de alguem que tenha permissão para isso.
- [x] Criar o arquivo `.travis.yml` e implementar logica de build do pelican e deploy no Github pages, em caso de build com sucesso.
- [x] Colocar o badget do travis no readme

C/C @humrochagf @cadu-leite @sergiomario você pode me ajudar com isso, ou me dar as permissões necessárias para eu mesmo fazer.

**Comment by luzfcb** [comment]
@magnunleno para que serve aqueles scripts ansible?

eles são necessários para fazer o pelican fazer o build do site corretamente?

**Comment by humrochagf** [comment]
adicionei lá o travis o arquivo e a chave

só falta o install e o script, quem tiver mais por dentro dos requisitos do projeto adiciona lá no .travis.yml os comandos pra montar o projeto e atualizar o gh-pages

**Comment by magnunleno** [comment]
@luzfcb Os scripts ansible são pra fazer o setup do ambiente automaticamente (instala dependências, configura virtualenv e instala pacotes no virtualenv).

**Comment by luzfcb** [comment]
obrigado @humrochagf e @magnunleno 
No fim de semana devo ter tempo de trabalhar nisto.

**Comment by luzfcb** [comment]
@magnunleno estou com problema na hora de fazer o build do [tema](https://github.com/pythonbrasil/pythonbrasil12-site/tree/master/theme), como no git blame diz que vc foi o ultimo a mexer nos arquivo de tema, suponho qe vc possa me ajudar com esse erro:

``` bash
$ make html
cd theme; make all
make[1]: Entering directory `/home/travis/build/luzfcb/pythonbrasil12-site/theme'
[ -d static/css ] || mkdir -p static/css
sass sass/main.scss static/css/main.css
make[1]: *** No rule to make target `static/css/main.css.map', needed by `css'.  Stop.
make[1]: Leaving directory `/home/travis/build/luzfcb/pythonbrasil12-site/theme'
make: *** [theme] Error 2
```

https://travis-ci.org/luzfcb/pythonbrasil12-site/builds/122419573

c/c @sergiomario

**Comment by luzfcb** [comment]
resolvido no pull-request https://github.com/pythonbrasil/pythonbrasil12-site/issues/27

**Comment by luzfcb** [comment]
@humrochagf obrigado. a sua correção no requirements do nodejs feitos no https://github.com/pythonbrasil/pythonbrasil12-site/pull/26 , resolveram os problemas que eu estava tento...
