### ISSUE TITLE
Link do blog não tá aparecendo na versão mobile

### ISSUE THREAD

**Issue by eliasdorneles** [pythonbrasil/pythonbrasil12-site#25]
Tentei ressucitar o menu com alguns xunxos no CSS, mas num consegui -- acabei escondendo o link das inscrições nos meus testes.

Alguém aí mais familiarizado com o tema consegue arrumar isso?
Idealmente acho que teria o ícone do hamburger button, né?

**Comment by sergiomario** [comment]
Testei no chrome mobile e está ok
