### ISSUE TITLE
Migrar para uma plataforma baseada em Python

### ISSUE THREAD

**Issue by magnunleno** [pythonbrasil/pythonbrasil12-site#6]
Talvez fosse interessante criar migrar o site para uma plataforma (gerador de site estático ou framework) baseado em Python.

Não é discriminação do Jekyll/Ruby, mas utilizar algo feito em Python amplia as possibilidade de customização, adaptação e hacking. Além de fomentar o uso de tecnologias da comunidade.

**Comment by sergiomario** [comment]
Aprovado!!

**Comment by sergiomario** [comment]
Só precisamos evitar derrubar o que está no ar, pois já está em avaliação por nossos possíveis apoiadores. :)

**Comment by luzfcb** [comment]
Só a titulo de conhecimento, o Tarek Ziadé criou recentemente uma ferramenta de edição para o Pelican

http://blog.ziade.org/2016/01/21/a-pelican-web-editor/

https://github.com/AcrDijon/henet

**Comment by magnunleno** [comment]
Reescrevi o site em Pelican. Favor avaliar a aderência com o site original antes de enviar um PR: http://magnunleno.github.io/pythonbrasil12-site/

**Comment by sergiomario** [comment]
Manda Pull Request. FIcou ótimo 0//

**Comment by sergiomario** [comment]
Migração concluída.
