### ISSUE TITLE
Criação de subdomínio

### ISSUE THREAD

**Issue by sergiomario** [pythonbrasil/pythonbrasil12-site#7]
Olá @filipecifali necessito de um subdompinio blog.pythonbrasil.org.br apontando para http://sergiomario.github.io/pythonbrasilblog/

Esse blog publicará informações relativas a Python Brasil 12

Obrigado.

**Comment by filipecifali** [comment]
Criado, depois é importante mover para o repositório da APyB que está em pythonbrasil.github.io, já está funcionando: 

dig +short blog.pythonbrasil.org.br                                                                                      [10:34:25]
sergiomario.github.io.
github.map.fastly.net.
23.235.39.133

**Comment by sergiomario** [comment]
Já transferi para http://pythonbrasil.github.io/ @filipecifali 

Entretanto acredito que tem que apontar para http://pythonbrasil.github.io/pythonbrasilblog/ agora.

Valeu.

**Comment by filipecifali** [comment]
@sergiomario feitoria, já modifiquei, pode ter um pouco de cache de DNS mas a princípio está OK:

dig +short blog.pythonbrasil.org.br @8.8.8.8                                                                             [11:11:42]
pythonbrasil.github.io.
github.map.fastly.net.
23.235.39.133

**Comment by sergiomario** [comment]
Grande @filipecifali o caminho pythonbrasil.github.io está apresentando erro 404 no github.

Acredito que tem que direcionar diretamente para http://pythonbrasil.github.io/pythonbrasilblog/ e não somente http://pythonbrasil.github.io. como está agora. Não?

Valeu

**Comment by filipecifali** [comment]
O apontamento não funciona dessa forma, que nem os outros apontamentos que temos para o github.io, a entrada de CNAME aponta para o usuário.github.io, exemplo:

 ❯ dig +short 2015.pythonbrasil.org.br                                                                                      [16:40:47]
pythonbrasil.github.io.
github.map.fastly.net.
23.235.39.133

 ❯ dig +short 2016.pythonbrasil.org.br                                                                                      [16:40:49]
pythonbrasil.github.io.
github.map.fastly.net.
23.235.39.133

Pode revisar as configurações do repositório ou me dar permissão para tal?

**Comment by sergiomario** [comment]
Saquei @filipecifali vou verificar. Qualquer coisa eu grito aí.

**Comment by sergiomario** [comment]
Funcionando 100% @filipecifali Obrigado 0/
